### ISSUE TITLE
不修复一下 java.lang.NumberFormatException: null？？？？？？

### ISSUE THREAD

**Issue by zhaohuanhui** [ausboyue/Okhttp-Multiple-Thread-Download-Demo#3]
at cn.icheny.download.DownloadTask.download(DownloadTask.java:156)

DownloadTask: start: false	http://music.wufazhuce.com/lmyuVg_Y-L37x6g93quntpGF2tyH

**Comment by zhaohuanhui** [comment]
cacheAccessFile.readLine(); 的问题不修复吗

**Comment by ausboyue** [comment]
贴一下log日志吧

**Comment by zhaohuanhui** [comment]
修复了。我改代码的问题、不过这个断点续传优化不够好。机器弱一点，太卡了。
